---
title: "Fake Data Code"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(scales)
library(formattable)
library(SuppDists)
library(reshape2)
```

```{r}
polls <- read.csv("senate_polls.csv")
```

```{r}
polls <- polls %>%
  filter(state == "Georgia") %>%
  filter(race_id == "7780" | race_id == "6271") %>%
  group_by(candidate_name)
polls
```

# Bootstrapping

```{r}
fake_polling <- function(distribution, size, min_spread, max_spread, candidate) {


fake_polls <- polls %>% 
  group_by(candidate_name, candidate_party, cycle) %>%
  #mutate(standard_deviation = sd(pct)) %>%
  #mutate(average_polling = mean(pct), standard_deviation = mean(standard_deviation)) %>%
  filter(candidate_name == "David A. Perdue" | candidate_name == "Jon Ossoff")

fake_polls <- fake_polls %>%
  mutate(candidate_party = recode(candidate_party, 
                                  `REP` = "R", 
                                  `DEM` = "D")) %>%
  filter(candidate_party == "R" | candidate_party == "D") %>% #2020 election will not have independents, only top two advance
  group_by(question_id) %>%
  #arrange(question_id, candidate_party) %>%
  select(question_id, poll_id, fte_grade, sample_size, candidate_name, candidate_party, pct) %>%
  filter(question_id != 123442 & question_id != 123443) %>%
  mutate(spread = pct - pct[candidate_party == "D"]) %>%
  mutate(spread2 = pct - pct[candidate_party == "R"]) %>%
  mutate(fake_spread = spread + spread2) %>%
  select(-spread, -spread2)
#fake_polls




fake_polls <- as.data.frame(round(distribution(size, min = min_spread, max = max_spread), 1))
colnames(fake_polls) <- "fake_spread"
fake_polls <- fake_polls %>%
  slice(rep(1:n(), each = 2)) %>%
  mutate(ID = row_number()) %>%
  mutate(candidate_name = case_when((ID %% 2 == 0) ~ "David A. Perdue",
                                    (ID %% 2 != 0) ~ "Jon Ossoff")) %>%
  mutate(fake_spread = case_when((ID %% 2 == 0) ~ fake_spread,
                                 (ID %% 2 != 0) ~ fake_spread * -1))

preboot_fake_plot <- ggplot(fake_polls, aes(fake_spread)) +
  geom_histogram(bins = 15)

fake_boot_spread <- map(1:size, ~sample(fake_polls$fake_spread, size = length(fake_polls), replace = TRUE)) %>%
  map_dbl(mean)

fake_boot_spread <- melt(fake_boot_spread)

boot_fake_plot <- ggplot(fake_boot_spread, aes(value)) +
  geom_histogram(aes(y=..density..)) +
  stat_function(fun = dnorm, args = c(mean = mean(fake_boot_spread$value), sd = sd(fake_boot_spread$value))) +
  geom_vline(xintercept = mean(fake_boot_spread$value)) +
  labs(title = "Bootstrapped Spreads")

#fit <- MASS::fitdistr(fake_boot_spread$value, "t")

reps <- size

empty_vec <- rep((fake_polls %>%
                    group_by(candidate_name) %>%
                    summarise(average_spread = mean(fake_spread)) %>%
                    filter(candidate_name == "David A. Perdue") %>%
                    select(average_spread)), reps) %>%
                    flatten_dbl()

fake_boot_spread <- fake_boot_spread %>% flatten_dbl()

Perdue <- (sd(fake_boot_spread) * rnorm(size, mean(fake_boot_spread), 
                                                     sd(fake_boot_spread))) + empty_vec 

win <- length(which(Perdue > 0)) / size #prob  winning
lose <- length(which(Perdue < 0)) / size #prob  losing

empty_vec_ossof <- rep((fake_polls %>%
                    group_by(candidate_name) %>%
                    summarise(average_spread = mean(fake_spread)) %>%
                    filter(candidate_name == "Jon Ossoff") %>%
                    select(average_spread)), reps) %>%
                    flatten_dbl()

Ossof <- (sd(fake_boot_spread) * rnorm(size, mean(fake_boot_spread), 
                                                     sd(fake_boot_spread))) + empty_vec_ossof 

win_ossof <- length(which(Ossof > 0)) / size #prob  winning
lose_ossof <- length(which(Ossof < 0)) / size #prob  losing



combined_probs <- melt(as.data.frame(cbind(Perdue, Ossof)))
combined_probs <- combined_probs %>% 
  group_by(variable) %>%
  mutate_at(vars(variable), as.character) %>%
  mutate(wining_color = case_when((variable == "Perdue" & value > 0) ~ "win",
                                   (variable == "Perdue" & value < 0) ~ "lose",
                                   (variable == "Ossof" & value > 0) ~ "win",
                                   (variable == "Ossof" & value < 0) ~ "lose"))
  #mutate(color_perdue = ifelse(value > 0, "red", "blue")) %>%
  #mutate(color_ossof = ifelse(variable 0 & value > 0, "blue", "red"))
combined_probs <- combined_probs %>%
  mutate(prob_winning = case_when((variable == "Perdue" & 
                                    wining_color == "win" ~ 
                                    length(which(Perdue > 0)) / size),
                                  (variable == "Perdue" & 
                                    wining_color == "lose" ~ 
                                    length(which(Perdue < 0)) / size),
                                  (variable == "Ossof" & 
                                    wining_color == "win" ~ 
                                    length(which(Ossof > 0)) / size),
                                  (variable == "Ossof" & 
                                    wining_color == "lose" ~ 
                                    length(which(Ossof < 0)) / size)))


ggplot((combined_probs %>% filter(variable == sprintf(candidate))), aes(value)) +
  geom_histogram(aes(fill = wining_color), color = "black", bins = 30) +
  ggthemes::theme_fivethirtyeight() +
  theme(axis.title = element_text()) + xlab("Spread") + ylab("Number of Observations") +
  theme(legend.title = element_blank()) +
  scale_x_continuous(breaks = seq((-1 * ceiling(max(combined_probs$value))) , (ceiling((max(combined_probs$value)))) , by = 1)) +
  labs(title = sprintf("Probability of Winning vs Losing for %s", candidate)) +
  annotate(geom = "text", x = mean(combined_probs$value) + (3 * sd(combined_probs$value)), y = 8000, 
           label = sprintf("Winning : %s", 
                           combined_probs %>% 
                             filter(wining_color == "win" & variable == candidate) %>% 
                             summarise(label_percent(accuracy = 0.01)(mean(prob_winning))) %>% 
                             select(-variable) %>% flatten_chr()),
           color = "#00BFC4") +
  annotate(geom = "text", x = mean(combined_probs$value) - (3 * sd(combined_probs$value)), y = 8000, label = sprintf("Losing : %s", 
                           combined_probs %>% 
                             filter(wining_color == "lose" & variable == candidate) %>% 
                             summarise(label_percent(accuracy = 0.01)(mean(prob_winning))) %>% 
                             select(-variable) %>% flatten_chr()), 
           color = "#F8766D")

}
```

```{r}
fake_polling(distribution = runif, size = 100000, min_spread = -4, max_spread = 4, candidate = "Perdue")
```
```{r}
mean(runif(1000, -2, 2))
```


```{r}
probability_winning_plot("Perdue")
```

```{r}
probability_winning_plot("Ossof")
```


```{r}
fake_polls <- polls %>% 
  group_by(candidate_name, candidate_party, cycle) %>%
  #mutate(standard_deviation = sd(pct)) %>%
  #mutate(average_polling = mean(pct), standard_deviation = mean(standard_deviation)) %>%
  filter(candidate_name == "David A. Perdue" | candidate_name == "Jon Ossoff")

fake_polls <- fake_polls %>%
  mutate(candidate_party = recode(candidate_party, 
                                  `REP` = "R", 
                                  `DEM` = "D")) %>%
  filter(candidate_party == "R" | candidate_party == "D") %>% #2020 election will not have independents, only top two advance
  group_by(question_id) %>%
  #arrange(question_id, candidate_party) %>%
  select(question_id, poll_id, fte_grade, sample_size, candidate_name, candidate_party, pct) %>%
  filter(question_id != 123442 & question_id != 123443) %>%
  mutate(spread = pct - pct[candidate_party == "D"]) %>%
  mutate(spread2 = pct - pct[candidate_party == "R"]) %>%
  mutate(fake_spread = spread + spread2) %>%
  select(-spread, -spread2)
fake_polls




fake_polls <- as.data.frame(round(runif(100000, min = -8, max = 8), 1))
colnames(fake_polls) <- "fake_spread"
fake_polls <- fake_polls %>%
  slice(rep(1:n(), each = 2)) %>%
  mutate(ID = row_number()) %>%
  mutate(candidate_name = case_when((ID %% 2 == 0) ~ "David A. Perdue",
                                    (ID %% 2 != 0) ~ "Jon Ossoff")) %>%
  mutate(fake_spread = case_when((ID %% 2 == 0) ~ fake_spread,
                                 (ID %% 2 != 0) ~ fake_spread * -1))

preboot_fake_plot <- ggplot(fake_polls, aes(fake_spread)) +
  geom_histogram(bins = 15)

fake_boot_spread <- map(1:100000, ~sample(fake_polls$fake_spread, size = length(fake_polls), replace = TRUE)) %>%
  map_dbl(mean)

fake_boot_spread <- melt(fake_boot_spread)

boot_fake_plot <- ggplot(fake_boot_spread, aes(value)) +
  geom_histogram(aes(y=..density..)) +
  stat_function(fun = dnorm, args = c(mean = mean(fake_boot_spread$value), sd = sd(fake_boot_spread$value))) +
  geom_vline(xintercept = mean(fake_boot_spread$value)) +
  labs(title = "Bootstrapped Spreads")

#fit <- MASS::fitdistr(fake_boot_spread$value, "t")

reps <- 100000

empty_vec <- rep((fake_polls %>%
                    group_by(candidate_name) %>%
                    summarise(average_spread = mean(fake_spread)) %>%
                    filter(candidate_name == "David A. Perdue") %>%
                    select(average_spread)), reps) %>%
                    flatten_dbl()

fake_boot_spread <- fake_boot_spread %>% flatten_dbl()

Perdue <- rnorm(100000, mean(fake_boot_spread), 
                                                     sd(fake_boot_spread)) + empty_vec 

n <- 100000

win <- length(which(Perdue > 0)) / n #prob  winning
lose <- length(which(Perdue < 0)) / n #prob  losing

empty_vec_ossof <- rep((fake_polls %>%
                    group_by(candidate_name) %>%
                    summarise(average_spread = mean(fake_spread)) %>%
                    filter(candidate_name == "Jon Ossoff") %>%
                    select(average_spread)), reps) %>%
                    flatten_dbl()

Ossof <- (mean(fake_boot_spread) * rnorm(n, mean(fake_boot_spread), 
                                                     sd(fake_boot_spread))) + empty_vec_ossof 


win_ossof <- length(which(Ossof > 0)) / n #prob  winning
lose_ossof <- length(which(Ossof < 0)) / n #prob  losing



combined_probs <- melt(as.data.frame(cbind(Perdue, Ossof)))
combined_probs <- combined_probs %>% 
  group_by(variable) %>%
  mutate_at(vars(variable), as.character) %>%
  mutate(wining_color = case_when((variable == "Perdue" & value > 0) ~ "win",
                                   (variable == "Perdue" & value < 0) ~ "lose",
                                   (variable == "Ossof" & value > 0) ~ "win",
                                   (variable == "Ossof" & value < 0) ~ "lose"))
  #mutate(color_perdue = ifelse(value > 0, "red", "blue")) %>%
  #mutate(color_ossof = ifelse(variable 0 & value > 0, "blue", "red"))
combined_probs <- combined_probs %>%
  mutate(prob_winning = case_when((variable == "Perdue" & 
                                    wining_color == "win" ~ 
                                    length(which(Perdue > 0)) / n),
                                  (variable == "Perdue" & 
                                    wining_color == "lose" ~ 
                                    length(which(Perdue < 0)) / n),
                                  (variable == "Ossof" & 
                                    wining_color == "win" ~ 
                                    length(which(Ossof > 0)) / n),
                                  (variable == "Ossof" & 
                                    wining_color == "lose" ~ 
                                    length(which(Ossof < 0)) / n)))


ggplot((combined_probs %>% filter(variable == sprintf("Perdue"))), aes(value)) +
  geom_histogram(aes(fill = wining_color), color = "black", bins = 30) +
  ggthemes::theme_fivethirtyeight() +
  theme(axis.title = element_text()) + xlab("Spread") + ylab("Number of Observations") +
  theme(legend.title = element_blank()) +
  scale_x_continuous(breaks = seq((-1 * ceiling(max(combined_probs$value))) , (ceiling((max(combined_probs$value)))) , by = 1)) +
  labs(title = sprintf("Probability of Winning vs Losing for %s", "Perdue")) +
  annotate(geom = "text", x = mean(combined_probs$value) + (3 * sd(combined_probs$value)), y = 8000, 
           label = sprintf("Winning : %s", 
                           combined_probs %>% 
                             filter(wining_color == "win" & variable == "Perdue") %>% 
                             summarise(label_percent(accuracy = 0.01)(mean(prob_winning))) %>% 
                             select(-variable) %>% flatten_chr()),
           color = "#00BFC4") +
  annotate(geom = "text", x = mean(combined_probs$value) - (3 * sd(combined_probs$value)), y = 8000, label = sprintf("Losing : %s", 
                           combined_probs %>% 
                             filter(wining_color == "lose" & variable == "Perdue") %>% 
                             summarise(label_percent(accuracy = 0.01)(mean(prob_winning))) %>% 
                             select(-variable) %>% flatten_chr()), 
           color = "#F8766D")

```
```{r}
sd(fake_boot_spread %>% flatten_dbl())

```


