---
title: "Election Function"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(scales)
library(formattable)
library(SuppDists)
library(reshape2)
```

Start by reading in the senate polling data. I have this as a .cvs so it will need to manually updated from time to time. 

```{r}
polls <- read.csv("senate_polls.csv")
```

```{r}
polls <- polls %>%
  filter(state == "Georgia") %>%
  filter(stage == "general") %>% #not modeling the jungle primary
  filter(race_id == "7780" | race_id == "6271") %>%
  filter(candidate_name == "David A. Perdue" | candidate_name == "Jon Ossoff" | 
           candidate_name == "Raphael Warnock" | candidate_name == "Kelly Loeffler") %>%
  group_by(candidate_name)
polls
```


```{r}
#bringing in old data

historical <- read.csv("us_senate_elections.csv")
historical <- historical %>%
  filter(state == "GA" |state == "Georgia") # just geogria

average_historical <- function(select_year){
  historical %>% 
  filter(year == select_year) %>%
  filter(office == "Senate") %>%
  group_by(candidate, year, party) %>%
  summarise(average_polling = mean(projected_voteshare), actutal_voteshare = mean(actual_voteshare),
            standard_deviation = mean(sd(projected_voteshare))) 
            #standard_deviation_actual = mean(sd(actual_voteshare)))
}

#Isakson vs Barksdale and Perdue vs Nunn
summary_table <- bind_rows(average_historical("2016"), average_historical("2014"))

#formattable(summary_table,
        #    align = c("l", rep("r", rep(NCOL(summary_table)))),
        #    list(`"Summary Statistics"` = formatter("span",
            #                  style = ~style(color = "gray"))))
```

```{r}
Perdue_vs_Ossoff <- polls %>% 
  group_by(candidate_name, candidate_party, cycle) %>%
  mutate(standard_deviation = sd(pct)) %>%
  summarise(average_polling = mean(pct), standard_deviation = mean(standard_deviation)) %>%
  filter(candidate_name == "David A. Perdue" | candidate_name == "Jon Ossoff")
Perdue_vs_Ossoff
```


```{r}
summary_table <- summary_table %>%
  rename("candidate_party" = party) %>%
  rename("cycle" = year) %>%
  rename("candidate_name" = candidate)
```

```{r}
total_data <- bind_rows(Perdue_vs_Ossoff, summary_table) %>%
  mutate(candidate_party = recode(candidate_party, 
                                  `REP` = "R", 
                                  `DEM` = "D")) %>%
  filter(candidate_party == "R" | candidate_party == "D") %>% #2020 election will not have independents, only top two advance
  group_by(cycle) %>%
  arrange(cycle, candidate_party) %>%
  mutate(spread = average_polling - lag(average_polling)) %>%
  fill(spread, .direction = "up") %>%
  mutate(spread = case_when(candidate_party == "R" ~ spread,
                            candidate_party == "D" ~ (-1 * spread))) #creating the spread for both candidates based on party. THis took be a longggg time to figure out
  #pivot_longer(cols = c(candidate_name, average_polling, standard_deviation), names_to = "variables", values_to = "times")
total_data
```


```{r}
election_fucntion <- function(candidate, nsim){
  choosen_race <- polls %>% 
    group_by(candidate_name, candidate_party, cycle, race_id) %>%
    mutate(standard_deviation = sd(pct)) %>%
    summarise(average_polling = mean(pct), standard_deviation = mean(standard_deviation)) %>%
    #filter(race_id == race)
    filter(candidate_name == candidate)

n <- nsim
johnson_dist <- rJohnson(n = n, 
                         parms = list(gamma = 0, 
                                      delta = .5, 
                                      xi = 0, 
                                      lambda = 2, 
                                      type = "SN"))

empty_vec <- rep((total_data %>% filter(cycle == "2020") %>% filter(candidate_name == "David A. Perdue"))$spread , n)
#perdue is in two races....casuing headaches here, fixed
overall_props <- (sd(johnson_dist) * johnson_dist) + empty_vec

probs_plot <- ggplot(data.frame(overall_props), aes(x = overall_props)) +
  geom_density() +
  geom_vline(xintercept = mean(overall_props))

win <- length(which(overall_props > 0)) / n #prob  winning
lose <- length(which(overall_props < 0)) / n #prob  losing

probs <- cbind(win, lose)

return(list(probs, probs_plot)) #for more than one output must be in a list
  
}

election_fucntion("David A. Perdue", 100000)
```



